### ISSUE TITLE
ETA for LaTeX package

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#100]
Dear stipub Team,
it's been more than a year since the release of stix v2.0 and the promised LaTeX package for the new fonts is not available yet. Using LuaLaTeX or LuaTeX is not an option, since they create very large files when including non-default fonts.
Also, the webpage hasn't been updated since December 1 of 2016. This repository/group has also been inactive in terms of response from you.
I think many of us would like to know an ETA for the LaTeX package, even if the release is not soon. We would like a concrete date like December 1 of 2018, even if it's December 1 2020. That way we could rest assured that a release is coming and we can wait. (Personally, I check the webpage every day with the hope that the LaTeX package has been released.)
Thanks in adavnce.

Reported by: dsejas

Original Ticket: [stixfonts/tracking/100](https://sourceforge.net/p/stixfonts/tracking/100)

**Comment by davidmjones** [comment]
The [stix2](/stipub/stixfonts/tree/master/STIXv2.0.0/Fonts/Type1) package is now available for download here and as the [stix2-type1](http://ctan.org/pkg/stix2-type1) collection on CTAN.

**Comment by keweili** [comment]
Thanks!
