### ISSUE TITLE
Wrong spacing Stix2 Type 1 Math 

### ISSUE THREAD

**Issue by jorge-fm** [stipub/stixfonts#102]
Way too much space between the integral sign and the upper and lower integration bounds. 
[type1stix.pdf](https://github.com/stipub/stixfonts/files/1934587/type1stix.pdf)
The type 1 fonts are unusable for math typesetting  in their present form. See attached example.

**Comment by mauvia2018** [comment]
Yes, this is a real problem. In this moment the latex package for stix2 type 1 is totally unusable. It is really something which should be fixed asap. Thanks (the font itself is very nice....)

**Comment by mauvia2018** [comment]
Thanks for the work. 

Just one question: should we expect soon a new release on CTAN of STIX2 type 1 package with this bug corrected?

**Comment by a-reisberg** [comment]
Is there any update on this? When will this be uploaded to CTAN? Thanks!

**Comment by mauvia2018** [comment]
From what I understand there are no plans to update stix2 type 1 on CTAN (too bad, in my opinion).
Anyway, I downloaded the amended files and did all the changes manually in my MikTeX distribution and all seems to work fine....

**Comment by a-reisberg** [comment]
@mauvia2018 Thanks! That's really too bad!
I have never installed tex fonts manually before. Is there a quick guide on how to patch stix 2 locally?
