### ISSUE TITLE
Add missing glyphs from unicode-math.sty

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#106]
The following 6 glyphs used by unicode-math.sty v0.8i are absent from STIX2Math v2.0.0:

Unicode | unicode-math
--------|--------------
U+23B7 RADICAL SYMBOL BOTTOM    | \sqrtbottom
U+23B8 LEFT VERTICAL BOX LINE   | \lvboxline
U+23B9 RIGHT VERTICAL BOX LINE  | \rvboxline
U+2422 BLANK SYMBOL             | \blanksymbol
U+1EEF0 ARABIC MATHEMATICAL OPERATOR MEEM WITH HAH WITH TATWEEL  | \arabicmaj
U+1EEF1 ARABIC MATHEMATICAL OPERATOR HAH WITH DAL                | \arabichad

The two Arabic glyphs would more appropriately be considered as part of #51, but since they are explicitly mentioned by unicode-math, it might make sense to consider them separately for compatibility.

**Comment by tiroj** [comment]
Will add the first four characters in 2.0.1, and placeholder designs for the two Arabic operators, to be reviewed when considering Arabic math support.

**Comment by davidmjones** [comment]
STIPub has decided not to pursue general Arabic support, but we would still like these two operators added for compatibility with the LaTeX unicode-math package.

**Comment by tiroj** [comment]
Logged for addition in 2.0.1

**Comment by tiroj** [comment]
[✓ Tiro internal]
