### ISSUE TITLE
STIX 1.1.1 fails to compile in pdflatex

### ISSUE THREAD

**Issue by cnruster** [stipub/stixfonts#107]
The tex system I use is MiKTeX 2.9. I am not interested in STIX 2, as it is no longer a Times New Roman font. I love STIX 1 font.

I downloaded the ZIP file from GitHub. I tried three ways to install STIX 1.1.1

1) Installing the opentype files in Windows 7. 

This has been very successful. Then I tried to use the font in xelatex. The commands I use in the latex file is:
```
\usepackage{fontspec}
\setmainfont{STIX}
```
The compilation was also successful. It was only that the SmallCaps is not supported. And I figured that it might become perfect if I use STIX in ordinary latex or pdflatex. So I continued to try the following:

2) Installing STIX from MiKTeX package

It turns out that MiKTeX 2.9 itself contains STIX 1 and 2. And I installed the relevant packages.  And I added the following line into my latex file:
`\usepackage{STIX}`

But the compilation fails, for all of latex, pdflatex, lualatex, xelatex.

3) Installing STIX 1.1.1 from the directory STIXv1.1.1\Fonts\stix-tds in the ZIP file

I copied all the files into my latex system according to the TDS structure, but the compilation still fails. 

The latex file is very simple:

```
\documentclass{article}
\usepackage{stix}
\begin{document}
Some text, and a math formula.
\end{document}
```

And the error message is the following:
Command Line:   pdflatex.exe --interaction=errorstopmode --synctex=-1 "stix.tex"
Startup Folder: D:\Academic\TexFiles

This is pdfTeX, Version 3.14159265-2.6-1.40.19 (MiKTeX 2.9.6700)
entering extended mode
(stix.tex
LaTeX2e <2018-04-01> patch level 5
Babel <3.20> and hyphenation patterns for 75 language(s) loaded.
(D:\Programs\MiKTeX29\tex\latex\base\article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(D:\Programs\MiKTeX29\tex\latex\base\size10.clo))
(D:\Programs\MiKTeX29\tex\latex\stix\stix.sty
(D:\Programs\MiKTeX29\tex\latex\base\textcomp.sty
(D:\Programs\MiKTeX29\tex\latex\base\ts1enc.def
(D:\Programs\MiKTeX29\tex\latex\base\ts1enc.dfu)))) (stix.aux)
(D:\Programs\MiKTeX29\tex\latex\base\ts1cmr.fd)
(D:\Programs\MiKTeX29\tex\latex\stix\ls1stix.fd)
(D:\Programs\MiKTeX29\tex\latex\stix\ls2stix.fd)
(D:\Programs\MiKTeX29\tex\latex\stix\t1stix.fd) [1{C:/Users/CYP/AppData/Local/M
iKTeX/2.9/pdftex/config/pdftex.map}] (stix.aux)Trying to make PK font t1-stixgeneral at 600 DPI...
The METFAONT mode is: ljfour
Running miktex-makemf.exe...

Sorry, but miktex-makemf did not succeed for the following reason:

  The t1-stixgeneral source file could not be found.

The log file hopefully contains the information to get MiKTeX going again:

  C:/Users/CYP/AppData/Local/MiKTeX/2.9/miktex/log/miktex-makemf.log

You may want to visit the MiKTeX project page, if you need help.

Running miktex-ttf2pk.exe...

Sorry, but miktex-makepk did not succeed for the following reason:

  PK font t1-stixgeneral could not be created.

The log file hopefully contains the information to get MiKTeX going again:

  C:/Users/CYP/AppData/Local/MiKTeX/2.9/miktex/log/miktex-makepk.log

You may want to visit the MiKTeX project page, if you need help.

_____________________________________________________________________

 PDFLaTeX Compilation Report (Pages: 0)

 Errors: 1   Warnings: 0   Bad Boxes: 0
_____________________________________________________________________

**In the STIXv1.1.1\Fonts\stix-tds directory, there are enc, map, otf, pl, tfm, pfb, vf files, but there are no afm, pfa files. Is that the problem? And I also noted that there are only 6 vf files.**

**Comment by cnruster** [comment]
Update:

The simple latex file given above can be compiled successfully by latex, and a DVI file is obtained. But it is only latex that can succeed.

Then I tried to make pdf by running dvipdfm. And again there is error. The error message:

Command Line:   dvipdfmx.exe "stix.dvi"
Startup Folder: D:\Academic\TexFiles

Trying to make PK font t1-stixgeneral at 600 DPI...
The METFAONT mode is: ljfour
Running miktex-makemf.exe...


Sorry, but miktex-makemf did not succeed for the following reason:



  The t1-stixgeneral source file could not be found.



The log file hopefully contains the information to get MiKTeX going again:



  C:/Users/CYP/AppData/Local/MiKTeX/2.9/miktex/log/miktex-makemf.log



You may want to visit the MiKTeX project page, if you need help.

Running miktex-ttf2pk.exe...

Sorry, but miktex-makepk did not succeed for the following reason:

  PK font t1-stixgeneral could not be created.

The log file hopefully contains the information to get MiKTeX going again:

  C:/Users/CYP/AppData/Local/MiKTeX/2.9/miktex/log/miktex-makepk.log

You may want to visit the MiKTeX project page, if you need help.

**Comment by davidmjones** [comment]
This is a question for the MikTeX community.  It sounds like you need to complete the installation process by updating the font maps.  In TeXLive, this would be done by running updmap or updmap-sys, but I don't know the details for MikTeX.
