### ISSUE TITLE
Upper and lower limits of integral are placed too far to the right

### ISSUE THREAD

**Issue by AboAmmar** [stipub/stixfonts#108]
When writing for example, `\[ \int_{0}^{\infty} x(t) dt \]`, the `0` and `∞` are rendered too far to the right of the integral sign.

**Comment by davidmjones** [comment]
This was fixed by #102.  Updated files should be available on CTAN soon, but the can download the latest files from here.

**Comment by AboAmmar** [comment]
Awesome, thank you so much
