### ISSUE TITLE
dot accents are not vertically aligned with i dot

### ISSUE THREAD

**Issue by tspiteri** [stipub/stixfonts#109]
Dot accents are not vertically aligned with the dot in the i character, making text look off when a character with a dot accent is next to an i. I'm attaching a screenshot of the Stix Two Text font showing the string “ċiġiż” with some guides to show the vertical misalignment. Also, the shape of the dot accent is skewed for the italics and bold italics versions. And in the bold italic version there is also visible misalignment between the dot accents for ċ and for ġ/ż.

![cigiz](https://user-images.githubusercontent.com/18604588/41240233-506a0954-6d9a-11e8-813f-b796dcf89e2a.png)

**Comment by davidmjones** [comment]
Thank you for the bug report.  I've tentatively assigned this to the v2.01 milestone.

[gh109.pdf](https://github.com/stipub/stixfonts/files/2091166/gh109.pdf)
[gh109.tex.gz](https://github.com/stipub/stixfonts/files/2091167/gh109.tex.gz)

**Comment by tiroj** [comment]
Logged to fix in 2.0.1. Not sure how this got through, as it's against our standard practice.

**Comment by tiroj** [comment]
[✓ Tiro internal]

**Comment by davidmjones** [comment]
Looks good.  The new more regularly shaped dot accents in the italic fonts are also very nice.
