### ISSUE TITLE
Add Invisible Mathematical Operators U+2061-U+2064

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#111]
Add appropriate support for the invisible mathematical operators described in section 22.6 of Unicode 10.  It's not clear to me that they should have visible glyphs, but they should not produce invalid code point errors.

Note added after further thought and some offline discussion: Consider adding a stylistic set that makes these and other normally invisible characters visible for editing and documentation purposes.

**Comment by tiroj** [comment]
Logged for 2.0.1 addition

**Comment by tiroj** [comment]
[✓ Tiro internal]

Note. Visible editing glyphs are provided, but so far no mechanism has been proposed or implemented to access these.
