### ISSUE TITLE
Add U+2423 OPEN BOX to text fonts.

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#112]

**Comment by tiroj** [comment]
Logged to add in 2.0.1

**Comment by tiroj** [comment]
Question: should these be characters be slanted in the italic Text fonts?

**Comment by davidmjones** [comment]
Yes, let's make them slanted in the italic fonts and heavier in the bold.

They were not slanted in STIX 1, but they are slanted in almost all of the other opentype italic fonts in the TeX Live distribution.  In addition, varying the style provides more flexibility; the user can choose the version they want.

**Comment by tiroj** [comment]
[✓ Tiro internal]

**Comment by tiroj** [comment]
I have opted to use Stylistic Set 20 (ss20) to access the curved variant form of this character, in order to have compatibility with the same substitution in the Math font.
