### ISSUE TITLE
Add dotless variants of U+2148 and U+2149 to STIX2 Math

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#114]
Add dotless glyph variant for
  -- U+2148 DOUBLE-STRUCK ITALIC SMALL I
  -- U+2149 DOUBLE-STRUCK ITALIC SMALL J

**Comment by tiroj** [comment]
Logged for 2.0.1 addition

**Comment by tiroj** [comment]
[✓ Tiro internal]
