### ISSUE TITLE
Add Nabla to PUA sans-serif Greek math alphabet

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#115]

**Comment by tiroj** [comment]
Suggest moving this to 2.1.0, since the PUA sans serif Greek isn't spec'd for 2.0.1

**Comment by tiroj** [comment]
I have not found a sans-serif regular weight Nabla in the old STIX non-Unicode fonts, so unless @davidmjones can provide one that is already in use, I will assign a new PUA to this glyph. Suggest: 0xE1F6, which is the next unused PUA in the sequence used for Greek sans serif alphabets in STIX Two Math.

**Comment by davidmjones** [comment]
I don't know of one, so go ahead with 0xE1F6.

**Comment by tiroj** [comment]
Added for v2.12
