### ISSUE TITLE
Restore PUA math alphabets from STIX 1

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#116]
STIX version 1 contains two math alphabets that are not (yet?) encoding by Unicode and that were inadvertently dropped in STIX Two:
* sans-serif italic Greek alphabet (U+E1B4–E1F6)
* and italic double struck alphabet (U+E154–E17C)

They should be restored.

**Comment by kenmcd** [comment]
This can be closed. 
All of these are in STIX Two Math v2.11 in the PUA in the same locations.
