### ISSUE TITLE
Add option for upright delimiters in italic text

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#119]

**Comment by tiroj** [comment]
Logged for addition in 2.0.1 (Text fonts only). Will need to determine how best to access (presumably one of the stylistic set features).

Q. I am presuming () [] {}. Any others?

**Comment by tiroj** [comment]
[✓ Tiro internal]

**Comment by tiroj** [comment]
This is now implemented in our internal build for the full-size () [] and {} in the Italic and Bold Italic Text fonts. I am mapping these in the Stylistic Set 2 (ss02) layout feature.

It has just struck me that perhaps users would want upright delimiters for the super and subscript variants too? Or is that overkill?

**Comment by davidmjones** [comment]
It looks beautiful.

Yes, if it's not too much trouble, let's combine it with the sups and subs features as well.

**Comment by tiroj** [comment]
I've spec'd to add the sup and sub upright delimiters in the next build of the italic Text fonts. The full size ones required a lot of kerning, so I might try to avoid this for the sup and sub by spacing them more widely.
