### ISSUE TITLE
Upright partial differential symbol (U+2202)

### ISSUE THREAD

**Issue by zepinglee** [stipub/stixfonts#123]
I am writing a LaTeX thesis template which is required to conform ISO 80000-2:2009 standard and I use `unicode-math` package to configure `stix2-otf` font. The `unicode-math` package has an option to choose upright or italic style of the symbol U+2202 partial differential but stix2 only provides an italic style.

A minimal example of XeLaTeX code:
```TeX
\documentclass{article}
\usepackage[math-style=ISO,bold-style=ISO,partial=upright]{unicode-math}
\setmathfont{STIX2Math.otf}
\begin{document}
\[
  \partial \symup{\partial} \mitpartial
\]
\end{document}
```

The output is:
![screen shot 2018-07-22 at 5 58 44 pm](https://user-images.githubusercontent.com/12290822/43044462-e6a743e2-8dd8-11e8-8d24-4bcc59b53938.png)

It would be better if `stix` provides an upright version of partial differential symbol since the ISO standard prefers the upright style.

**Comment by tiroj** [comment]
Logged to fix in 2.0.1

Proposed fix is to make the upright form the default for U+2202 (regular) and U+1D6DB (bold) in the Math font, so for the italic it would be necessary to use U+1D715 and U+1D74F.

Q. At present, we have –script and –scriptscript scaling variants for the italic (U+1D715) partial diff signs. Am I right in thinking that for the ISO standard it would also be helpful to add –script and –scriptscript variants of the revised upright U+2202?

**Comment by tiroj** [comment]
[✓ Tiro internal]

**Comment by davidmjones** [comment]
That seems like a good approach.  Adding script and scriptscript variants might as well wait until we decide whether to implement it more widely.

**Comment by tiroj** [comment]
I went ahead and added the script and scriptscript variants of the upright U+2202, but not for the bold U+1D6DB.
