### ISSUE TITLE
Make Stix a variable font

### ISSUE THREAD

**Issue by Marrib** [stipub/stixfonts#125]
I think the title says it all.

Please consider doing that, it would be so great.

References and examples:
[https://en.wikipedia.org/wiki/Variable_fonts](https://en.wikipedia.org/wiki/Variable_fonts)
https://hacks.mozilla.org/2018/09/variable-fonts-arrive-in-firefox-62

**Comment by tiroj** [comment]
With the sources as they currently exist — a mix of inherited STIX 1 outlines, newly designed outlines, and division of STIX 2 into Text and Math font families —, I'm not sure the cost of the significant work required would be justified by the benefits. The latter would be limited to interpolation of the STIX Two Text weights, and even that would involve a lot of work to make all the outlines compatible between the two weight masters. I'm not sure that having access to an intermediate semibold weight range is worth that kind of effort.

More enticing would be the possibility of adding optical size specific design masters to the Text fonts, and implementing these in an 'opsz' variable font axis, which could then automatically display the appropriate size design for anything from footnote/caption sizes up to display design for book and journal titling. In developing STIX Two, we did create interpolable size-specific designs for a subset of the characters, so we could use these to fine-tune the –script and –scriptscript scaling glyphs used for super- and subscript letters and numbers in equation layout. We've talked a bit with AMA folk about building these subsets out into size-specific design masters.

At present, the MATH table is one of the few aspects of the OpenType specification that was not affected by the addition of variable font capabilities to the format. In the last part of my TYPO Labs 2017 presentation on ideas for glyph-level — as distinct from font-level — variable technology, I spoke about some possibilities for math layout* but this is still very much speculative.

*https://www.youtube.com/watch?v=MuuAmG_qer8
The math bit begins at [42.25](https://youtu.be/MuuAmG_qer8?t=2545)

**Comment by davelab6** [comment]
@tiroj and I are discussing how Google Fonts can support this effort :)

**Comment by kevinbarabash** [comment]
@tiroj has any progress been made on what you talked about in the video?

**Comment by tiroj** [comment]
No progress on math-specific variable behaviours. I recently exchanged emails with some MathML folk regarding using variable interpolation for ssty weight and proportion adjustments, but it's still purely hypothetical.
