### ISSUE TITLE
\pm sits below baseline

### ISSUE THREAD

**Issue by John02139** [stipub/stixfonts#126]
The plus/minus symbol sits too low.  Running LuaLaTeX.
```
   \documentclass[11pt]{article}
   \usepackage{mathtools,unicode-math}
   \setmathfont{STIX Two Math}  

   \begin{document}
   \[ F(x) = a\pm b \]
   \end{document}
```
<img width="673" alt="screen shot 2018-09-05 at 8 22 34 pm" src="https://user-images.githubusercontent.com/39748301/45127986-76e13600-b149-11e8-8119-78fea351be9b.png">

A LaTeX work-around is in TEX-SE [here.](https://tex.stackexchange.com/questions/243936/symbol-pm-is-lower-than-the-number-next-to-it)

**Comment by tiroj** [comment]
Logged for 2.0.1 fix

**Comment by tiroj** [comment]
[✓ Tiro internal]
