### ISSUE TITLE
Replace sans-serif and monospace Mathematical Alphanumeric Symbols

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#129]
These are lesser-used math alphanumeric ranges that were not
prioritised for updating in STIX 2.0.0.  The existing Latin roman
(upright) sans-serif design is serviceable, but could be improved,
while the Greek needs more extensive work; the italics are currently
mechanically slanted versions of the roman, and could be replaced with
designed italics to better match the treatment of text italics.  The
monospaced design has many awkward shapes and wobbly outlines and
should be completely replaced.

Range      | Description
---------- | --------------------
U+1D5A0--U+1D5D3 | Sans-serif symbols
U+1D5D4--U+1D607 | Sans-serif bold symbols
U+1D608--U+1D63B | Sans-serif italic symbols
U+1D63C--U+1D66F | Sans-serif bold italic symbols
U+1D670--U+1D6A3 | Monospace symbols
U+1D756--U+1D78F | Sans-serif bold Greek symbols
U+1D790--U+1D7C9 | Sans-serif bold italic Greek symbols
U+1D7E2--U+1D7EB | Sans-serif digits
U+1D7EC--U+1D7F5 | Sans-serif bold digits
U+1D7F6--U+1D7FF | Monospace digits

Plus related characters elsewhere in the standard (e.g. Letterlike
Symbols).

**Comment by tiroj** [comment]
[✓ Tiro internal]
