### ISSUE TITLE
Revise fraktur and double-struck Mathematical Alphanumeric Symbols

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#130]
Range            | Description
---------------- | --------------------
U+1D504--U+1D537 | Fraktur symbols
U+1D538--U+1D56B | Doulbe-struck symbols
U+1D56C--U+1D59F | Bold Fraktur symbols
U+1D7D8--U+1D7E1 | Double-struck digits

**Comment by tiroj** [comment]
[✓ Tiro internal]
