### ISSUE TITLE
U+2026 HORIZONTAL ELLIPSIS 

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#133]
The horizontal ellipsis is spaced too tightly, especially compared to U+22EF MIDLINE HORIZONTAL ELLIPSIS.

**Comment by tiroj** [comment]
Please confirm whether this is specific to the Math font, or also the Text fonts. In the latter, we've spaced the ellipsis dots fairly tightly as one of the reasons for a separate ellipsis character — contra simply typing three periods — is to take up less horizontal space and leave less whitespace in the line.

**Comment by davidmjones** [comment]
Lets make the change in all of the fonts.  The more widely spaced dots work better for mathematical publishing and it would be awkward if there were a mismatch between math and text.
