### ISSUE TITLE
Latin Extended and IPA Extension coverage

### ISSUE THREAD

**Issue by moyogo** [stipub/stixfonts#141]
The Latin Extended and IPA Extension coverage is odd.

The lowercase characters ƈƒƙƚƥƭɓɖɗɠɨɫɵʈʉʋ have small cap glyph variants but their uppercase Latin Extended-B characters are not present: ƇƑƘȽƤƬƁƉƊƓƗⱢƟƮɄƲ.

The IPA Extension characters have uppercase used in orthographies or other phonetic notations, except for Ɛ, these are missing and some don’t have small cap glyph variants: ⱯⱭⱰƁƆƉƊƏꞫƓꞬƔꞍꞪƗƖꞮⱢꞭƜⱮƝƟⱤƦƩꞱƮɄƱƲɅƷꞲꞰ.

**Comment by tiroj** [comment]
Yes. Odd.

The original STIX fonts included a bunch of IPA stuff for phonetics use, but not corresponding uppercase characters when these IPA letters also occur in natural language orthographies (mostly African). When we came to specify smallcap coverage for the STIX Two Text fonts, I based this in part on what I had done for the Brill types, which included smallcaps of IPA coverage. 

Closing this for now, but would certainly consider adding the uppercase characters to support more natural language orthographies if funding were available.
