### ISSUE TITLE
bad magic number in STIX2Math.otf

### ISSUE THREAD

**Issue by GergelyBuday** [stipub/stixfonts#143]
I have downloaded STIX2Math.otf from 

https://github.com/stipub/stixfonts/blob/master/OTF/STIX2Math.otf

I get

$ otfinfo -i STIX2Math.otf
otfinfo: STIX2Math.otf: not an OpenType font (bad magic number)

This is otfinfo 2.107

This came from trying to use STIX2Math.otf in \setmathfont

**Comment by davidmjones** [comment]
How did you download the file?  If I go to the page you linked to and click on the "Download" button, I get the correct file.  If that doesn't work, could you try cloning the repo or downloading the zip file and see if that works for you?
