### ISSUE TITLE
missing \fi in stix.sty is not fixed in CTAN

### ISSUE THREAD

**Issue by muzimuzhi** [stipub/stixfonts#144]
The problem reported in #61 (and should be fixed in v1.0.0) still exists in the current v2.0.0a on CTAN.

Check the line containing `\def\stix@dotlessi{\ifmmode\imath\else\i}` of this dtx file on CTAN: http://mirrors.ctan.org/fonts/stix2-type1/stix2.dtx.

Fixing is as simple as substituting `\i` for `\fi`.

**Comment by davidmjones** [comment]
Fixed in v2.0.2, which is live now on CTAN.  It might take a couple of days to reach all of the mirrors.

**Comment by muzimuzhi** [comment]
thanks
