### ISSUE TITLE
u+027cc looks broken when compiling with LuaTeX using unicode-math

### ISSUE THREAD

**Issue by matteocoder** [stipub/stixfonts#145]
Hello and thank you for providing this great font.
When compiling a document with LuaTeX and the unicode-math package, the long division symbol (u+027cc) looks broken.
![long division stix2](https://user-images.githubusercontent.com/22897138/61463836-83dbd200-a975-11e9-9852-300950258558.PNG)

It is easy to see the problem even without zooming.

I'm using TeX Live 2019 for Windows, LuaTeX 1.10, unicode-math 0.80 and the STIX Two Math font 2.01.

Thank you for your attention.

**Comment by matteocoder** [comment]
I am reopening this issue because I thought that it was a problem with unicode-math, but according to [this discussion](https://github.com/wspr/unicode-math/issues/527)
the glyph itself has a problem.

**Comment by tiroj** [comment]
Reference: https://github.com/stipub/stixfonts/issues/183
