### ISSUE TITLE
Make math variants available as character variants

### ISSUE THREAD

**Issue by kevinbarabash** [stipub/stixfonts#149]
There doesn't seem to be a way to access math variants of characters like `square root` and various delimiters when using STIX in the browser.  Since browsers do support character variants maybe those could be used to support the math variants.  The current workaround for this issue is repackaging the math variants into separate fonts based on size.

**Comment by tiroj** [comment]
Hmm. This sounds like a lot of work for what will probably only be a partially useful workaround. Better support for math layout in browsers is surely the long term solution.

Closing this for now, but will reconsider if STI Pub considers worth exploring.

**Comment by tiroj** [comment]
The STIX Two Text fonts are now built as variable fonts with a weight axis. There’s been some talk about using variable technology for growing delimiters and optically tuning ssty/ssty2 scaling variants*, but nothing concrete yet. Having a variable axis that only affects a subset of characters in a font is technically possible, but it isn’t something that font tools really handle well.

* https://youtu.be/MuuAmG_qer8?t=2555
