### ISSUE TITLE
Missing asterisk with package listings and stix2

### ISSUE THREAD

**Issue by Fubaxiusz** [stipub/stixfonts#151]
When using package **listings** with **stix2** asterisk * is missing, only blank space displayed.
![image](https://user-images.githubusercontent.com/34406163/77687955-8defaf00-6f9f-11ea-9b05-0330ae047cd5.png)

Here is code to reproduce the issue:
```
\documentclass[a4paper,11pt]{article}
\usepackage{stix2}
\usepackage{listings}

\begin{document}
\begin{lstlisting}[
caption={A simple C program with missing \*.},
language=C
]
// Entry point for the program
int main(const int argc, const char* argv[]) {

    // Print some output
    /* Print some output for */
    printf("Hello world!\n");

    return 0*10;
}
\end{lstlisting}
\end{document}

```

**Comment by xsrvmy** [comment]
Apparently `listings` package substitutes `*` for `\textasteriskcentered`.
For workaround, `\renewcommand{\textasteriskcentered}{*}`

**Comment by robot6** [comment]
This is very interesting.  I have a similar problem.  I am writing a document using the eskdx package in Russian.  In math mode, all the minuses become asterisks.  And actually, when I put an asterisk in, it becomes something that looks quite like the \guilsinglleft symbol.

**Comment by tiroj** [comment]
@davidmjones Is this issue specific to some flavour(s) of TeX? Do we need to do anything in the fonts?

**Comment by xsrvmy** [comment]
Looks like the OP was using the Type1 version of stix2, in which `\textasteriskcentered` probably has no mapped character.
`\textasteriskcentered` does work with the unicode version of the font so this shouldn't be an issue with the otf font.

**Comment by tiroj** [comment]
Thanks. Closing.
