### ISSUE TITLE
U+205F MEDIUM MATHEMATICAL SPACE is too wide

### ISSUE THREAD

**Issue by dscorbett** [stipub/stixfonts#153]
U+205F MEDIUM MATHEMATICAL SPACE is far too wide. Here is <U+0078 LATIN SMALL LETTER X, U+205F MEDIUM MATHEMATICAL SPACE, U+007A LATIN SMALL LETTER Z>:
![x z](https://user-images.githubusercontent.com/1124347/80244860-b66ad780-8637-11ea-90c3-8343f9fbc368.png)

**Comment by tiroj** [comment]
Confirmed bug. Will set to 455 units (4/18 em) in v2.12

**Comment by tiroj** [comment]
Correction: set to 222 units on 1000 unit per em design scale. This applied to both Math and Text fonts for v2.12.
