### ISSUE TITLE
ff broken in newer versions

### ISSUE THREAD

**Issue by dbenjaminmiller** [stipub/stixfonts#155]
![image](https://user-images.githubusercontent.com/43855846/82383354-9a224680-99fb-11ea-87b0-d719148cf463.png)

Compare with the ligature in the Type 1 font:

![image](https://user-images.githubusercontent.com/43855846/82383413-bde58c80-99fb-11ea-8de7-1671025cb44b.png)

**Comment by tiroj** [comment]
Coincidentally, I just spotted this myself this morning. Will be fixed in the 2.1.0 release (which is getting close, I think).

**Comment by dbenjaminmiller** [comment]
Great minds think alike, then. What else is planned for the new release? Looking forward to it.
