### ISSUE TITLE
Overbar is misplaced

### ISSUE THREAD

**Issue by ksdbeach** [stipub/stixfonts#164]
The overbar (e.g., $\bar{v}_x$) is properly centered in with \usepackage{stix}, but it's misaligned (offset to the right) with \usepackage{stix2}.
![vbar-stix](https://user-images.githubusercontent.com/71112893/92852417-4e354c00-f3b4-11ea-993c-be85d86ad12a.png)
![vbar-stix2](https://user-images.githubusercontent.com/71112893/92852436-53929680-f3b4-11ea-86e0-154b918d7f22.png)

**Comment by tiroj** [comment]
Reinvestigate for v2.20

**Comment by tiroj** [comment]
Closing. Reference more complete issue description: https://github.com/stipub/stixfonts/issues/135
