### ISSUE TITLE
Wrong glyph for U+23B7 RADICAL SYMBOL BOTTOM

### ISSUE THREAD

**Issue by dscorbett** [stipub/stixfonts#165]
U+23B7 RADICAL SYMBOL BOTTOM does not connect with other radical symbol pieces, which are unified with the box drawing symbols U+2502 and U+250C. [L2/00-159](https://www.unicode.org/L2/L2000/00159-ucsterminal.txt) says that “the vertical stroke must be truly vertical and centered, not slanted.” Here it is below U+2502.
![│␤⎷](https://user-images.githubusercontent.com/1124347/94873811-36367280-041e-11eb-817d-727bab10642a.png)

**Comment by tiroj** [comment]
Both forms are included in the font (and also parts used in automated assemblies). Will switch the encoding to the upright glyph. Thanks.

**Comment by tiroj** [comment]
Hmm. The upright variant seems not to be used in any layout, and is probably a artefact from older STIX fonts or unrealised plan. Totally different glyphs are used in assemblies.

I can revise /uni23B7/ to be vertical and align with the box drawing symbols, but using box draw characters to build radical symbols seems like an old hack. How widespread is that vs using MATH table handling?

**Comment by dscorbett** [comment]
I don’t know. I imagine it’s not common nowadays.

**Comment by tiroj** [comment]
Fixed v2.10 b152
