### ISSUE TITLE
Status of v2.1.0?

### ISSUE THREAD

**Issue by dbenjaminmiller** [stipub/stixfonts#170]
I don't meant to push anyone — 2020 has not been an easy year. But originally 2.1.0 was announced for Q1 2020, and it has been moved on the stixfonts.org website with each passing quarter ­— is the plan still indeed to release the new version in 2020? Or sometime next year?

**Comment by tiroj** [comment]
I can't speak to the release plans, but I can report that 2.1.0 sources and build script were delivered to STI Pub in October. I presume they are being tested, but will follow up with @davidmjones this week.

**Comment by davidmjones** [comment]
One way or another these will be released by the end of the year.  We've finished what testing we have time for.  I hope to finish adequate release notes and documentation this week.

**Comment by dbenjaminmiller** [comment]
Anything I can do to help out with the release notes/documentation?

**Comment by davidmjones** [comment]
Many thanks for the offer, but I think we have things under control now.  Unless something unexpected happens, 2.10 should be released by the beginning of next week.
