### ISSUE TITLE
Problem with zip file STIXv2.0.0-type1.zip

### ISSUE THREAD

**Issue by jhk10-cambridge** [stipub/stixfonts#171]
I have downloaded STIXv2.0.0-type1.zip to my Windows 10 machine but when I try to open it I get the message that the archive is invalid.  I had no problem with STIXv2.0.2.zip

Please can anyone advise?

Thank you

James K.

**Comment by davidmjones** [comment]
I checked the file and it looks ok to me.  My guess is that something happened to the file when you downloaded it.  Try downloading a fresh copy and hopefully that will fix the problem.  I also added a file of md5 checksums so you can check the integrity of the file you downloaded.

**Comment by jhk10-cambridge** [comment]
Thank you.  Still no change, unfortunately. But I am getting a colleague to try it on a Linux box and will report back.

**Comment by jhk10-cambridge** [comment]
Problem solved.  I downloaded it a different way and now I can open it.  Thank you - sorry for troubling you.

**Comment by davidmjones** [comment]
No problem.  Glad it worked out.
