### ISSUE TITLE
Different angle of contrast with latin and greek letters

### ISSUE THREAD

**Issue by zepinglee** [stipub/stixfonts#172]
The glyphs of latin letter “o” and greek letter “ο” (omicron) in STIX Two Math version 2.0.1 are as below.
<img width="862" alt="Screen Shot 2020-12-17 at 12 33 48" src="https://user-images.githubusercontent.com/12290822/102444605-907dc180-4064-11eb-9753-b1796e1d4742.png">
The direction of the thin parts (red lines) of the glyphs are different. This also applies to other lowercase greek letters. Is it a feature of design or a bug?

In the original Times font, these directions are consistent.
<img width="846" alt="Screen Shot 2020-12-17 at 12 44 06" src="https://user-images.githubusercontent.com/12290822/102445053-9031f600-4065-11eb-8ef6-ac2f77685cb6.png">

The above illustrations are produced with TeX Live 2020.
```latex
\documentclass{article}
\usepackage{amsmath}
\usepackage{unicode-math}
\setmainfont{Times}
\setmathfont{STIX2Math.otf}
\setmathfont{XITSMath-Regular.otf}[version=xits]
\begin{document}
Times: o \symbol{"03BF} \textit{o \symbol{"03BF}} \par
STIX Two Math: $o$ $\omicron$ \par
\mathversion{xits}
XITS Math: $o$ $\omicron$ \par
\end{document}
```

**Comment by dbenjaminmiller** [comment]
This is intentional. You may want to read this: https://medium.com/@gerryleonidas/designing-greek-typefaces-eac0de7767cc

**Comment by zepinglee** [comment]
> This is intentional. You may want to read this: https://medium.com/@gerryleonidas/designing-greek-typefaces-eac0de7767cc

Thanks!
