### ISSUE TITLE
FAILS reported for Variable Fonts

### ISSUE THREAD

**Issue by vv-monsalve** [stipub/stixfonts#174]
These are the main Fails reported from checks performed on files pulled at commit [9192a17](9192a17bf3e983ee76abaf78d1f5d8b223bffc30).

The Semibold instances, both for Roman and Italic fonts, should be named SemiBold to match the fallback names on the [Weight Axis Registry](https://github.com/google/fonts/blob/master/axisregistry/weight.textproto) for the GF API.

<details>
<summary>🔥 <b>FAIL:</b> Check variable font instances have correct names</summary>

* [com.google.fonts/check/varfont_instance_names](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/varfont_instance_names)

* 🔥 **FAIL** Following instances are not supported: 
	- Semibold Italic

Further info can be found in our spec https://github.com/googlefonts/gf-docs/tree/master/Spec#fvar-instances [code: bad-instance-names]

</details>

**Comment by vv-monsalve** [comment]
<details>
<summary>🔥 <b>FAIL:</b> Space and non-breaking space have the same width?</summary>

* [com.google.fonts/check/whitespace_widths](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/hmtx.html#com.google.fonts/check/whitespace_widths)

* 🔥 **FAIL** Space and non-breaking space have differing width: The space glyph named space is 225 font units wide, non-breaking space named (uni00A0) is 256 font units wide, and both should be positive and the same. GlyphsApp has "Sidebearing arithmetic" (https://glyphsapp.com/tutorials/spacing) which allows you to set the non-breaking space width to always equal the space width. [code: different-widths]

</details>

**Comment by tiroj** [comment]
Fixed for b157
