### ISSUE TITLE
Update CTAN package.

### ISSUE THREAD

**Issue by dbenjaminmiller** [stipub/stixfonts#177]
Someone needs to update the [CTAN package](https://www.ctan.org/pkg/stix2-otf). I can do it if you're OK with it.

**Comment by davidmjones** [comment]
There are a few small changes pending to satisfy Google Font's requirements.  Once those are finalized, I'll update CTAN.

**Comment by davidmjones** [comment]
v2.11 is live on CTAN now.  It might take a few days for it to propogate to all of the mirrors.
