### ISSUE TITLE
Oldstyle Yen feature code issue (v2.11)

### ISSUE THREAD

**Issue by kenmcd** [stipub/stixfonts#181]
The `onum` feature code for the Yen currency symbol is incorrect.

Current:  
`sub yen.OP by yen.OP;`
![1  StixText Oldstyle Yen before](https://user-images.githubusercontent.com/844920/104622078-ab345d80-5645-11eb-8180-79cf196530e1.png)

Should be:  
`sub yen by yen.OP;`
![2  StixText Oldstyle Yen after](https://user-images.githubusercontent.com/844920/104622155-bf785a80-5645-11eb-92b2-24fa4374f949.png)

```plaintext
lookup x.onum {
    sub zero by zero.OT;
    sub one by one.OT;
    sub two by two.OT;
    sub three by three.OT;
    sub four by four.OT;
    sub five by five.OT;
    sub six by six.OT;
    sub seven by seven.OT;
    sub eight by eight.OT;
    sub nine by nine.OT;
    sub Euro by Euro.OP;
    sub dollar by dollar.OP;
    sub sterling by sterling.OP;
    sub yen.OP by yen.OP;  # should be  sub yen by yen.OP;
} x.onum;
```

**Comment by tiroj** [comment]
Fixed in VOLT projects and input.ttf Text fonts for v2.12
