### ISSUE TITLE
[STIXTwoTextVF-Roman.vfj] In `n`, x pos of `top` anchor in `n` does not compensate for width change across masters

### ISSUE THREAD

**Issue by twardoch** [stipub/stixfonts#199]
x position of `top` anchor in `n` upright masters is the same, i.e. has not width-specific displacement: 

![](https://recordit.co/IDiYr0qGzD.gif)

This results in a "wobble" as you interpolate, because the marks over `n` attach in different width-relative x positions:

![](https://recordit.co/dVPzSx1ioz.gif)

**Comment by twardoch** [comment]
👍

**Comment by tiroj** [comment]
Fixed.
