### ISSUE TITLE
[STIXTwoTextVF-Roman.vfj] `longsslash` has mismatching contour order

### ISSUE THREAD

**Issue by twardoch** [stipub/stixfonts#200]
`longsslash` in upright has mismatching contour order

![](https://recordit.co/qRc8nxMjBs.gif)

Also issue with `slashcomb`: 

![](https://recordit.co/9R3TDgexj0.gif)

**Comment by twardoch** [comment]
👍

**Comment by tiroj** [comment]
Fixed.
