### ISSUE TITLE
[STIXTwoTextVF-Roman.vfj] Big difference in `b.f_` & `h.f_` masters would cause problems in extrapolation

### ISSUE THREAD

**Issue by twardoch** [stipub/stixfonts#201]
With just interpolation, the big difference in vertical placement of the topleft node between upright masters of `b.f_` & `h.f_` is not a problem, but with extrapolation will cause issues even if the entire design would be OK for some extrapolation:

![](https://recordit.co/Z2wMGiGfJ7.gif)

**Comment by tiroj** [comment]
There are reasons why the OT variable font format is not designed to extrapolate beyond axis extrema.

The angle there has to change, and I don’t see a tidy way to do that which doesn’t involve one or more points travelling in ways that will cause problems if extrapolated. Let me know if you have a suggested architecture.

**Comment by tiroj** [comment]
I’ve restructured this for v2.13, so that there is less vertical movement, but at some point extrapolation is always going to explode things.

**Comment by twardoch** [comment]
Imagine how you'd solve that if you had a Black :) In the top part of b & h intended for ligatures, insert an extra node in the diagonal segment to keep the angle of the diagonal part that sticks out, but then move the lower mode up.

**Comment by twardoch** [comment]
Something like this would be a clean solution, no? 

<img width="1398" alt="scr- 2021-04-26 at 23 03 52" src="https://user-images.githubusercontent.com/519108/116150527-c3575680-a6e3-11eb-9bff-4678f6e34467.png">

<img width="1398" alt="scr- 2021-04-26 at 23 03 46" src="https://user-images.githubusercontent.com/519108/116150538-c6524700-a6e3-11eb-943d-cdb499206aea.png">

**Comment by twardoch** [comment]
(Ofc I agree that at *some* point, it will :) )

**Comment by tiroj** [comment]
Yes, that's pretty much what I ended up doing. There is still a fair amount of movement, since the graphical relationship of the top of the ascender to the hook of the f changes so much as the weight increases.
