### ISSUE TITLE
[STIXTwoTextVF-Roman.vfj] `c.bigyus.smcp` design of inner structure would cause extrapolation issues

### ISSUE THREAD

**Issue by twardoch** [stipub/stixfonts#203]
In upright `c.bigyus.smcp` design of the inner structure is OK as is, but if one were to extrapolate, it would cause issues. The reson is the placement of the lower node inside the fork. 

![](https://recordit.co/PhZNpShTDk.gif)

**Comment by tiroj** [comment]
Restructured in v2.13.

**Comment by twardoch** [comment]
👍
