### ISSUE TITLE
eshcurl in Upright has a problem

### ISSUE THREAD

**Issue by twardoch** [stipub/stixfonts#208]
<img width="1209" alt="scr- 2021-05-03 at 06 51 55" src="https://user-images.githubusercontent.com/519108/116842227-206b7480-abdc-11eb-8509-9373c3228f58.png">

<img width="1209" alt="scr- 2021-05-03 at 06 52 01" src="https://user-images.githubusercontent.com/519108/116842232-23666500-abdc-11eb-91c4-5b5c32c83800.png">

Extrapolated Light at 65:

<img width="1209" alt="scr- 2021-05-03 at 06 52 10" src="https://user-images.githubusercontent.com/519108/116842237-25c8bf00-abdc-11eb-9fd4-8a94415118d7.png">

**Comment by tiroj** [comment]
Ack. We just approved v2.13 fixes in the dev repo, and I don’t want to crack the sources again. Since this is affecting extrapolation, not interpolation, I will log this for the next round of work.
