### ISSUE TITLE
Roman variable vjf has not paired anchors on Bold Layer

### ISSUE THREAD

**Issue by typoland** [stipub/stixfonts#210]
Glyphs tildelongcomb  tildelongcomb.cap  breveinvertedlongcomb and breveinvertedlongcomb.cap have anchors on Bold layer not corresponding to Normal layer.

**Comment by tiroj** [comment]
Will check this, but I believe those anchors are not used in any case, so probably were just not deleted in the Bold master. The GPOS mark positioning is implemented via the VOLT sources, whose lookups make use of the VFJ anchor data but are filtered to ensure interpolability.

[The dounle-width combining marks in Unicode are a pain-in-the-neck. They never work nicely without silly amounts of contextual variation in positioning based on the width and height of the glyphs they cover, so I tend not to try anchoring them, but just left them sit on the boundary between the glyphs.]

**Comment by typoland** [comment]
It will work with FontLab. But I’m making vfj parser for myself and used your file to test it. And it failed on anchors in those four glyphs.

**Comment by tiroj** [comment]
Our own VFJ-to-VOLT parser ignored them, I think, but I will delete them from the VFJ source in the next round of fixes. Thanks for catching this.

PS. Want to join a conversation re. VFJ parsers with @davelab6 and some others?

**Comment by typoland** [comment]
Why not, but I'm afraid my current English is out of proper conversation.

**Comment by typoland** [comment]
My parser parses only MM-like vjf.. It's tot good for more-than-one-dimensional Variable Fonts.

**Comment by tiroj** [comment]
**b171.** Deleted unmatched Bold anchors in roman VFJ source.
