### ISSUE TITLE
Enhancement: adjust mathbb letter weight

### ISSUE THREAD

**Issue by Griger** [stipub/stixfonts#212]
Hi,
first of all, I think that STIX is one of the best fonts for scientific texts, and it should be the standard in the future.

I am not a font designer, so I may be wrong, but I think that the weight for the mathbb characters does not match with the rest of the font glyphs.

![image](https://user-images.githubusercontent.com/7707062/122384506-0d361d80-cf6c-11eb-9943-5038c5134089.png)

In the previous example it could be seen that the `\mathbb{C}` character, ℂ, has a different weight from the rest of glyphs in the image.

Many thanks for your time.

**Comment by tiroj** [comment]
This is the designed weight of the double-struck characters, which are constructed from a mostly monolinear stroke weight, and in which the enclosed areas between the strokes represents the struck-out portion of the letter. This makes them naturally lighter structure than the other letters. If you imagine the struck-out portion being filled in, then they would be similar weight:

<img width="834" alt="Screenshot 2021-06-17 at 8 20 08 AM" src="https://user-images.githubusercontent.com/5614500/122426986-925a0c00-cf45-11eb-8ac2-23a24614550d.png">

**Comment by Griger** [comment]
Thanks for your quick answer, I see your point and I will close the issue.

Thanks for your time and your font.
