### ISSUE TITLE
Inconsistency between brackets and \llbracket and \rrbracket symbol

### ISSUE THREAD

**Issue by Griger** [stipub/stixfonts#230]
Hi,

first of all, many thanks for this awesome font that I am using to write my PhD thesis. I have working for a while with this font and I have encountered a certain inconsistency between some symbols. Here I show an image of these symbols:

![image](https://user-images.githubusercontent.com/7707062/149923088-5f176657-fec7-4721-a30a-64146476cff3.png)

The LaTeX code to obtain this output is:

```latex
\llbracket p \rrbracket \lbrack p \rbrack 
```
The `\llbracket` and `\rrbracket` symbols come from the `stmaryrd` package. As you can see, the stroke and the height of both symbols (sorry if I am using the wrong terms) do not match. Could it be solved? The corresponding Unicode symbols for `\llbracket` and `\rrbracket` are U+27E6 and U+27E7, respectively.

Many thanks for your time.

**Comment by tiroj** [comment]
That should be fixed in the new v2.20 work we delivered to STI Pub in December, which is currently undergoing testing. We coordinated the heights of all the delimiters in the Math font, including the basic punctuation set that were previously as inherited from the Text font.

**Comment by Griger** [comment]
And it seems that the corners of `\llbracket` and `\rrbracket` are rounder while `\lbracket` and `\rbracket` are not. Is this intended?

On the other hand, when will v2.20 be released? Many thanks for your great work :smile:.

**Comment by tiroj** [comment]
Oh. Those dblstruck brackets are not STIX Two Math: somehow you are getting fallback to a different font. This is how STIX Two Math displays U+27E6 and U+27E7:

![image](https://user-images.githubusercontent.com/5614500/150015470-e9059eaf-29d5-47fe-8232-d3a5e48e6c02.png)


I don’t know when v2.20 will be released. That is decided by STI Pub.

**Comment by Griger** [comment]
Oh, I see. Do you know how I can use this proper symbols in LaTeX? 

Currently, I load the package `stmaryrd` in order to be able to use these symbols, and it seems that this package overload the symbols of the font.

**Comment by tiroj** [comment]
Sorry, I’ve not idea. I just make the fonts. :)

Paging @davidmjones

**Comment by Griger** [comment]
I think that I have found the solution to use the proper symbols for the dblstruck brackets. Previously, I was using the package `stmaryrd` in order to be able to use the `\llbracket` and `\rrbracket` commands to include these symbols, and it seems that this package uses its own symbols for this.

However, I have realized that STIX is one of the LaTeX fonts that supports the `unicode-math` package (users should love STIX for that :heart_eyes:). Then, you can check the list of [`unicode-math` symbols](https://osl.ugr.es/CTAN/macros/unicodetex/latex/unicode-math/unimath-symbols.pdf) and find which is the macro of unicode-math for the desired symbol and see whether this is available on the font (STIX in this case or not).

STIX widely supports the unicode-math symbol set, so in this case you only should use the macros `\lBrack` and `rBrack` to get these dblstruck brackets without using the `stmaryrd` package. And then you get the proper STIX dblstruck brackets :smile:.

I will leave this response here in case someone could find it useful for their use of STIX in LaTeX. I close this issue with this comment.

Again, many thanks for your time, and thanks for this awesome project.
