### ISSUE TITLE
URI friendly variable font filenames

### ISSUE THREAD

**Issue by pkra** [stipub/stixfonts#244]
A tiny silliness but I stumbled over it once again so perhaps others have, too. 

The filenames for the variable font files currently require URI escaping (due to `[` and `]`). While this is mostly healed by user agents, it can cause issues.

**Comment by tiroj** [comment]
The variable font filenames are in a format specified by Google Fonts. I’ll direct their attention to this issue. Can you provide more specific details of the problem as it affects particular user agents?

**Comment by pkra** [comment]
> The variable font filenames are in a format specified by Google Fonts. 

Ah, thanks for clarifying.

> I’ll direct their attention to this issue. 

No need.

> Can you provide more specific details of the problem as it affects particular user agents?

It's not a technical issue as such. If a user references the fonts correctly (i.e., URI escapes), everything is fine. If they don't, it's mostly fine. Most users won't notice there's a problem even if authors forget about it.
