### ISSUE TITLE
Small caps for Swedish Å for Regular StixTwoText.otf

### ISSUE THREAD

**Issue by JimEBlevins** [stipub/stixfonts#245]
Stix Two Text has correct **small caps** for the Swedish **Å** in the _Italic_, **Bold**, and **_BoldItalic_** fonts. 

For the **Regular** font, I get the lower-case **å**! 

Details:
In 2022, I installed the latest release (2021) of STIX Two Text. I use MicroTeX's LaTeX2e distribution, LuaTeX, and the FontSpec package to compile a PDF file in TeXstudio (in which I view the PDF). I also checked my pdf file with Adobe Reader.

**Comment by tiroj** [comment]
I am not able to reproduce this in any of my test environments.

**Comment by JimEBlevins** [comment]
Sorry! 
It was a coding error on my part. 

Sorry for trouble.
