### ISSUE TITLE
Why in STIXTwoText-Regular.pdf U+0374 is printed in red?

### ISSUE THREAD

**Issue by jsbien** [stipub/stixfonts#248]
The explanation "Characters shown in red (e.g., U+01CE) are not directly supported but can be synthesized by a Unicode-
aware shaping engine." does not seem suitable for 'GREEK NUMERAL SIGN' U+0374 which is not a precomposed character.

**Comment by davidmjones** [comment]
Unicode canonical decompositions aren't limited to precomposed characters.  They can also be used to indicate that one character can be substituted for another.

If you look at the entry for 0374 in the characters names list following the Greek and Coptic code chart, you'll see

    ≡ 02B9 ' modifier letter prime

You can also see this in UnicodeData.txt, where field 5 is the canonical decomposition:

    0374;GREEK NUMERAL SIGN;Lm;0;ON;02B9;;;;N;GREEK UPPER NUMERAL SIGN;;;;

Another example is the Angstom sign U+212B, which is canonically equivalent to U+00C5 LATIN CAPITAL LETTER A WITH RING ABOVE.
