### ISSUE TITLE
`\sun` default to `\odot`

### ISSUE THREAD

**Issue by Firestar-Reimu** [stipub/stixfonts#267]
https://en.wikipedia.org/wiki/Astronomical_symbols

standard astronomical symbol (used on every textbook and article on astronomy) is U+2609, which look like `\odot` (and many astronomers simply use `\odot` to express the sun)

but stix2 use "white sun with rays" to match `\sun`

**Comment by Enivex** [comment]
This mapping has nothing to do with the font itself, but [unicode-math](https://ctan.org/pkg/unicode-math?lang=en)

As you can see from https://ftp.fagskolen.gjovik.no/pub/tex-archive/macros/unicodetex/latex/unicode-math/unimath-symbols.pdf `\sun` maps to U+263C
