### ISSUE TITLE
Missing OpenType features / glyphs for old style numbers and calligraphic letters

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#58]
Old style numbers should be provided by the OpenType feature "onum" on digits.

Calligraphic style should be provided by the OpenType feature "salt" or "ssXX" on "mathematical script" Unicode characters.

See for example Asana in
http://fred-wang.github.io/MathFonts/
https://github.com/fred-wang/MathFonts/blob/master/Asana/mathfonts.css

For XITS:
https://github.com/khaledhosny/xits-math/issues/32
https://github.com/khaledhosny/xits-math/issues/40

Reported by: fred-wang

Original Ticket: [stixfonts/tracking/58](https://sourceforge.net/p/stixfonts/tracking/58)

**Comment by fourpoints** [comment]
Calligraphic (chancery) and roundhand (script) should be made available through the variation selector characters included in Unicode 14.

If I'm not mistaken, `U+FE00` corresponds to `ss01` and `U+FE01` corresponds to `ss01`.

* [The Unicode Standard, Version 14.0, Page 12](https://www.unicode.org/versions/Unicode14.0.0/ch22.pdf)
* [XML Entity Definitions for Characters (3rd Edition), Variant Mathematical Character](https://w3c.github.io/xml-entities/index.html#chars_math-variant-tables)

**Comment by davidmjones** [comment]
> Calligraphic (chancery) and roundhand (script) should be made available through the variation selector characters included in Unicode 14.
> 
> If I'm not mistaken, `U+FE00` corresponds to `ss01` and `U+FE01` corresponds to `ss01`.
> 
>     * [The Unicode Standard, Version 14.0, Page 12](https://www.unicode.org/versions/Unicode14.0.0/ch22.pdf)
> 
>     * [XML Entity Definitions for Characters (3rd Edition), Variant Mathematical Character](https://w3c.github.io/xml-entities/index.html#chars_math-variant-tables)

Already planned as part of issue #218

**Comment by tiroj** [comment]
Confirmed: this is implemented in the font currently in internal beta.
<img width="413" alt="image" src="https://user-images.githubusercontent.com/5614500/175999518-e026d9c8-06f5-44df-a0fb-cb5b254d0cfa.png">
Because the chancery forms are the default in the STIX Two Math font, only the FE01 mappings are needed in the fomat 14 cmap subtable.

The <ss01> feature will still need to be used for lowercase characters, as Unicode, in their wisdom, decided to define variation selector sequences only for the uppercase.

**Comment by fourpoints** [comment]
Thanks @davidmjones I was searching for "calligraphic" in the issues and missed that one.

@tiroj On that row 50, `Zscript.ss01` is the only one with `0x00fe00` in that image, is that correct?

**Comment by tiroj** [comment]
Good catch! Thank you.

**Comment by tiroj** [comment]
@davidmjones I have fixed this in the sources in the dev repo but you will need to run the build process and update the Fonts folder for testing and before pushing to the public repo.
