### ISSUE TITLE
Provide WOFF metadata.xml

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#63]
The OFL FAQ asks users willing to distribute STIX as Web fonts to "Make sure the font file contains the needed copyright notice(s) and licensing information in its metadata."

http://scripts.sil.org/cms/scripts/page.php?item_id=OFL-FAQ_web#b2706942

Please provide such metadata:

http://www.w3.org/TR/WOFF/#Metadata

(See https://sourceforge.net/p/stixfonts/tracking/54/ for a request about providing WOFF versions of the STIX fonts rather than the version modified for MathJax)

Reported by: fred-wang

Original Ticket: [stixfonts/tracking/63](https://sourceforge.net/p/stixfonts/tracking/63)

**Comment by tiroj** [comment]
The tool we used to generate the WOFF and WOFF2 files did not have a provision to add metadata. We will investigate options for this when we reach that stage of the 2.0.1 build.

**Comment by davidmjones** [comment]
This is on hold pending a review of our tool chain for producing the fonts.  Since the metadata is optional and is primarily intended to provide a place to document license restrictions, it's not a high priority for an open source font such as STIX.

**Comment by davidmjones** [comment]
This is optional for webfonts, and mainly exists for the benefit of non-open source fonts, in which foundries or web publishers might want to include data to identify the licensee. This doesn't apply to the STIX fonts.
