### ISSUE TITLE
Wrong glyph at U+1D752 in STIX Two Math

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#79]
The glyph at U+1D752 MATHEMATICAL BOLD ITALIC KAPPA SYMBOL in STIX Two Math is wrong; instead of a KAPPA the glyph is a KOPPA

Reference: http://tex.stackexchange.com/questions/342579/bold-italic-varkappa-in-stix-2

Reported by: eg9

Original Ticket: [stixfonts/tracking/79](https://sourceforge.net/p/stixfonts/tracking/79)

**Comment by tiroj** [comment]
Logged to fix in 2.0.1

**Comment by tiroj** [comment]
[✓ Tiro internal]
