### ISSUE TITLE
unfortunate assignment of slashed zero to <ss07>

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#80]
the slashed zero -- an alternate form of U+2205 (the slashed circle) representing the empty set -- has been assigned to stylistic set <ss07>, which is otherwise populated by "small" versions of various large operators.

when this stylistic set is chosen, probably only for the slashed zero, the display version of the summation sign (U+2211) will not be set at its proper large size.

this is shown, along with an output example, at http://chat.stackexchange.com/transcript/message/33854284#33854284

Reported by: bbeeton

Original Ticket: [stixfonts/tracking/80](https://sourceforge.net/p/stixfonts/tracking/80)

**Comment by davidmjones** [comment]
Here's the missing image from the original sourceforge ticket:

![slash-zero-ss07](https://user-images.githubusercontent.com/6642132/41253791-6e98f31e-6d8f-11e8-8901-08b979262289.png)

**Comment by tiroj** [comment]
Logged to remove from ss07 in 2.0.1

We'll be adding support for Unicode standard variation selector sequences for math characters in 2.0.1, which will include the slashed zero form of the empty set symbol.

Q. Do you still also want this variant mapped in a stylistic set feature? If so, which one?

**Comment by tiroj** [comment]
[✓ Tiro internal]
