### ISSUE TITLE
Glyphs uni02A9 fhook.smcp are different between Regular and Bold (hook and no hook)

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#84]
In STIXTwoText-Regular, the glyphs "uni02A9" and "fhook.smcp" have a hook but in STIXTwoText-Bold, they don't have a hook. One of them is right and the other is wrong. 

Reported by: twardoch

Original Ticket: [stixfonts/tracking/84](https://sourceforge.net/p/stixfonts/tracking/84)

**Comment by tiroj** [comment]
Logged to fix in 2.0.1

**Comment by tiroj** [comment]
[✓ Tiro internal]
