### ISSUE TITLE
Tilde U

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#85]
Hello! 
\tilde{U} looks terrible in latex, please see the attached image.
Hope this can be improved.
Thank you!

Reported by: snkarl16

Original Ticket: [stixfonts/tracking/85](https://sourceforge.net/p/stixfonts/tracking/85)

**Comment by davidmjones** [comment]
Imported sample from sourceforge: 
![utilde](https://user-images.githubusercontent.com/6642132/41254716-4aeace44-6d92-11e8-88c4-621da470a250.jpg)

**Comment by tiroj** [comment]
Unable to reproduce. Tilde is correctly positioned in precomposed glyph for U+0168.

Possibly some software is displaying this with combining accent mark, which lacks GPOS mark positioning in the STIX fonts (possible 2.1.0 work item?)

**Comment by davidmjones** [comment]
A long overdue clarification: the issue is with the math font:

[gh085.pdf](https://github.com/stipub/stixfonts/files/2600977/gh085.pdf)

**Comment by tiroj** [comment]
The Math font doesn't contain an italic Utilde character. This appears to be the italic math alphanumeric U character with a combining (non-italic) tilde. In math layout, different mechanisms are used for positioning marks than in general text layout. The height position and .cap variant substitutions appear to be working correctly, so we'll see what we can do about the horizontal position when we come to edit the MATH table.

**Comment by tiroj** [comment]
[✓ Tiro internal]

Updated flattened math accent default offset and also MATH table Top Accent Attachment (the latter also extended in 2.0.1 to provide generally better positioning on more bases).
