### ISSUE TITLE
Incorrect metrics in bold sans serif italic

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#88]
When running a test suite of math spacing against various OpenType math fonts,
I noticed that STIX Two Math has incorrect glyph metrics in bold sans serif italic.

Bold sans serif Italic letters with ascenders or descenders bump into adjacent delimiters
or overprint an attached exponent. The spacing is almost the same as for bold sans serif upright.

The attached sample document shows the test ouput with LuaTeX 0.95 (TeX Live 2016 final).

Reported by: uvieth

Original Ticket: [stixfonts/tracking/88](https://sourceforge.net/p/stixfonts/tracking/88)

**Comment by davidmjones** [comment]
Sample documents from original sourceforge ticket:
[math-test-spacing-stix.pdf](https://github.com/stipub/stixfonts/files/2091583/math-test-spacing-stix.pdf)
[math-test-spacing-stix.tex.gz](https://github.com/stipub/stixfonts/files/2091584/math-test-spacing-stix.tex.gz)

**Comment by tiroj** [comment]
The sans serif alphabets will be thorough revised in 2.0.1, so this issue should also get fixed.

**Comment by tiroj** [comment]
[✓ Tiro internal]

Note: the sans serif alphanumerics have been replaced, and the delimeters have been replaced. When working on MATH table updates we will check these relationships.
