### ISSUE TITLE
Publish fonts on bower and npm registries, and/or a cdn

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#91]
Today an unofficial github registry is used to retrieve fonts from bower: https://github.com/laravelfanatic/stix-fonts
It will be interesting to have an official bower and/or npm delivery to retrieve them threw these tools, and, as a developer, to stay up-to-date with the latest releases.

Reported by: fxgentil

Original Ticket: [stixfonts/tracking/91](https://sourceforge.net/p/stixfonts/tracking/91)

**Comment by pkra** [comment]
If there's interest in publishing to NPM, I'm happy to set it up.

**Comment by davidmjones** [comment]
Closed duplicate of issue #92
