### ISSUE TITLE
Publish fonts on bower and npm registries, and/or a cdn

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#92]
Today an unofficial github registry is used to retrieve fonts from bower: https://github.com/laravelfanatic/stix-fonts
It will be interesting to have an official bower and/or npm delivery to retrieve them threw these tools, and, as a developer, to stay up-to-date with the latest releases.

Reported by: fxgentil

Original Ticket: [stixfonts/tracking/92](https://sourceforge.net/p/stixfonts/tracking/92)

**Comment by pkra** [comment]
Duplicate of #91.

**Comment by davidmjones** [comment]
The just-completed reorganization of the directory structure and addition of a 2.0.0 tag should make the STIX Two fonts conveniently accessible via popular CDNs (jsdelivr.com, rawgit.com, gitcdn.xyz, raw.githack.com, and probably others).  An npm package would require additional work.  If you still feel it's necessary, let us know and we'll see what we can do.
