### ISSUE TITLE
Missing APL Glyphs

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#93]
Currently the STIX Two release has fixed availability for a number of APL glyphs, but there are still notable omissions that are not covered. These include the following:

⌸ U+2338
⌺ U+233A
⌾ U+233E
⎕ U+2395
⍤ U+2364
⍥ U+2365
⍸ U+2378

I am sure that there are others. Here's a page that has a reasonably good list of them:

http://aplwiki.com/UnicodeAplTable

Most of these are covered, but there are some glaring omissions. 

Reported by: arcfide

Original Ticket: [stixfonts/tracking/93](https://sourceforge.net/p/stixfonts/tracking/93)

**Comment by davidmjones** [comment]
This is a subset of #110, but I've tentatively assigned it to milestone v2.0.1

**Comment by tiroj** [comment]
[✓ Tiro internal]

Note: These APL characters have all been added, plus others from the aplwiki documentation. The set does not cover all the APL characters in Unicode, but could be extended in future. Existing APL character glyphs have been revised for consistency in width and vertical alignment.

**Comment by davidmjones** [comment]
More complete coverage of Miscellaneous Technical block is under consideration for the next release (#110).
