### ISSUE TITLE
Boxing Glyphs for APL Characters have inappropriate proportions

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#94]
The current version of STIX Two glyphs for boxing characters in APL have inappropriate proportions.

⎕⌷⍞⌸⌹

Some of these glyphs are missing entirely, but generally, all of the boxes are too wide. The Squished QUAD (⌷) could also maybe benefit from some height, but that's probably not absolutely necessary, as making them smaller in overall width will probably suffice to create the "taller" feeling.

These characters historically arose from an overstriking of [ and ] for the skinny quad, and a juxtaposition of [] for the QUAD character. Thus, the boxing is far too wide for them as they currently are. 

Reported by: arcfide

Original Ticket: [stixfonts/tracking/94](https://sourceforge.net/p/stixfonts/tracking/94)

**Comment by tiroj** [comment]
[✓ Tiro internal]

Note: I added a bunch of common APL characters (but not all those included in Unicode), and revised the existing ones for consistency. Revised glyphs include those mentioned in the original issue as well others.
