### ISSUE TITLE
Overleftrightarrow symbol

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#97]
When trying to use \overleftrightarrow the symbol appear as attached image

~~~
\documentclass{article}

\RequirePackage{unicode-math}
\setmainfont{STIX2Text-Regular.otf}
\setmathfont{STIX2Math.otf}
\setmathfont[range="1D752]{STIX Math}

\begin{document}
$\overleftrightarrow{AXX}$
\end{document}
~~~

Reported by: hussamsalah

Original Ticket: [stixfonts/tracking/97](https://sourceforge.net/p/stixfonts/tracking/97)

**Comment by tiroj** [comment]
Will need to better understand this bug before confirming how to fix.

**Comment by tiroj** [comment]
Thanks. We'll look into this. I presume it means we need to add MATH table horizontal extension information for this character (not my department).

**Comment by tiroj** [comment]
[✓ Tiro internal]

Added assembly information to Horiztonal Glyph Variants in MATH table.
