### ISSUE TITLE
Upsilon is indistinguishable from Y

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#98]
As in the title.

Reported by: sfncmp

Original Ticket: [stixfonts/tracking/98](https://sourceforge.net/p/stixfonts/tracking/98)

**Comment by tiroj** [comment]
At present, the design of U+03A5 is identical to Latin Y — one of the valid forms of Upsilon —, providing contrast with the variant U+03D2. No action planned on this.
