### ISSUE TITLE
z, is awkward in italic

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#99]
In the italic and bold italic fonts, when a comma follows a lowercase z, it sits almost on top of the z's tail. My current workaround is to bump the tracking up to about 100 for this combination, but not all word processing systems give the user control of tracking.

Reported by: practik

Original Ticket: [stixfonts/tracking/99](https://sourceforge.net/p/stixfonts/tracking/99)

**Comment by davidmjones** [comment]
Thanks for the bug report.  I've tentatively assigned this to the v2.0.1 milestone.

[gh099.pdf](https://github.com/stipub/stixfonts/files/2091181/gh099.pdf)
[gh099.tex.gz](https://github.com/stipub/stixfonts/files/2091182/gh099.tex.gz)

**Comment by practik** [comment]
Cheers, David. It occurs to me now that `z,` is probably not the only awkward combination. Taking a quick look, I'd say that `z.` and `z;` are pretty tight as well.

**Comment by davidmjones** [comment]
Yes, I'm sure you're right.  Much of the kerning of STIX Two, especially for parts of the font that were only partially updated, was carried over from the original STIX fonts.  We do plan to carry out a more systematic review when possible.

**Comment by tiroj** [comment]
Actually, the STIX Two fonts were kerned from scratch, with new OpenType GPOS class and exception kerning. It's possible some combinations were missed or could be improved, though, and z + punctuation could definitely benefit from positive kerns to increase the space between. Thanks for catching this.
